services:
  nginx:
    image: nginx:2002
    build: ./srcs/requirements/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./srcfs/requirements/wordpress:/var/www/html

    restart: unless-stopped
    env_file:
      - ./srcs/.env